### ISSUE TITLE
[Aesthetics] Bigger icons on Controller header

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#215]
I've noticed that the icons in the other sidebar windows are slightly bigger than the Controller ones. 

Here's a comparison:

![icon_diferences](https://github.com/user-attachments/assets/df95d73b-bc6c-4f37-b8c1-500bd8fdbab2)

From the editor, I saw that the Controller icon should be at ~135% to reach the same size.

This is not just an aesthetic thing; bigger icons would also improve the _clickability_.

**Comment by JorgeR81** [comment]
Yeah, the Controller's header could be a little taller.
At least the top row, to accommodate the larger icons.

![header](https://github.com/user-attachments/assets/c52863bc-30c6-4f8d-bfb0-a5409fc5cc5c)

**Comment by chrisgoringe** [comment]
I've made them bigger. I've also moved to using the pi icons (https://www.primefaces.org/diamond/icons.xhtml) that Comfy, so they can be more consistently controlled; they don't have a gear one so I've used the caret-down (feel free to see if you think there's a better choice!)

**Comment by LukeG89** [comment]
@chrisgoringe I would replace it with one of the following:

(a gear one, but probably  this would be confused as a settings menu)
![gear](https://github.com/user-attachments/assets/0bfb0e41-8fc6-4c09-80c8-8c06b95e275d)
(this is my favorite)
![controlles](https://github.com/user-attachments/assets/2f765d35-8e63-4ca9-ba71-4f1bb8c834e9)
![star](https://github.com/user-attachments/assets/9cfd593f-891c-4b7a-bfba-12ce2686757e)

Another couple of candidates could be:

![bolt](https://github.com/user-attachments/assets/18891522-9d52-4586-a458-847932caa9f0)
![list](https://github.com/user-attachments/assets/ee9ce77e-0d7d-4f43-88e5-2f13bef57361)

**Comment by JorgeR81** [comment]
The current icon makes sense to me, because it's like an arrow pointing down, and it makes the panel stack expand down the column.  

I don't mind keeping it.

But, I think the **`bolt`** would look cool :) 

This could mean the more "dangerous" settings, less user friendly, that you want to keep hidden, and used only when necessary.
You know, like these "high voltage" panels boxes, that you're not supposed to mess with. 

---

It's not a perfect icon, but the other icons also have issues:

- **`gear`** - used by ComfyUI. And also, it would mean all settings ( not just advanced settings )

- **`sliders`** - Same issue. It would mean all settings. That's why it worked as the Controller icon in the Sidebar, but not here.

- **`star`** - this would indicate "favorites", but the "advanced controls" would be less used ( it would be the opposite ).

- **`list`** - Same issue. It would mean all settings.

**Comment by LukeG89** [comment]
@JorgeR81 I made these proposals because the caret-down icon doesn't feel as "advanced", and also it is smaller compared to the refresh icon.

There are not many options to choose from, I just picked the "best" candidates to me.

- Gear: I agree with you, it means "settings". Forget about it.
- List: Completely random, just because it's a big icon! 😆
- Star: It's because they are "special" controls.
- Sliders: Seems the more accurate and bigger icon to me.
- Bolt: Can be a good alternative, it feels like a "power tools" option, but it's not the biggest icon. 

@chrisgoringe What do you think?

**Comment by chrisgoringe** [comment]
For the time being, the bolt...

See the 1.1 branch!

**Comment by LukeG89** [comment]
I like it!

You've made the floating controller already?? That was fast!⚡
