### ISSUE TITLE
Respond to window resizing (was [Question] Fullscreen mode: How floating windows should behave?)

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#224]
In this initial stage, the floating window has this behavior in fullscreen mode:

- Remains the same size and place when you enter
- Moves the window up when you exit
- Fits full-height windows when you exit, and keep the new size when you enter again

https://github.com/user-attachments/assets/86c9a20f-5546-446a-8bad-0cde146395b9

Now I wonder: Is this the correct behavior? How to avoid unwanted moving and resizing?

**Comment by chrisgoringe** [comment]
The current logic is:

- the controller window should at all times be fully visible
- if it is off the edge of the screen, it should be moved (as little as possible)
- if that is not possible (because it is too tall, for instance), it should be shrunk (as little as possible)

That's definitely correct behaviour when the user is moving the controller.

However, when the window is resized, there are two issues:

- the controller doesn't react until you interact with it (need to watch for window resize events)
- the above rules result in the controller size being changed if you shrink the window then grow it again

I think the first should be fixed. The second, I think is the natural way for it to work given the three rules above, and I doubt the cost/benefit of trying to do otherwise.

**Comment by LukeG89** [comment]
Maybe the only thing I would change is the window position, following the browser window resize like Queue and Graph Canvas menus:


https://github.com/user-attachments/assets/d41a0309-a30a-4b84-99f2-c56f9cb76843

**Comment by chrisgoringe** [comment]
I think I might have found a better solution. See what you think. If you resize the window down then up, it should return to the size and position it was before (unless you interact with it in between, in which case the new position takes preference).

Basic logic is:
- we have a preferred dimension, which is the last position/size set by the user dragging it
- the display position is a modified version of the preferred position

**Comment by JorgeR81** [comment]
Can't we have rules like these ? 

1 - If a Controller border touches a canvas border, it will always do so, unless the user changes this ( by dragging it or resizing it )

2 - The position for the Controller will be changed, when needed, to to follow rule 1

3 - If changing the position is not enough to fulfill rule 1, dimensions will be changed.

This last one is in case the Controller has full height ( if 2 opposite canvas borders are touched by the controller ).
To fulfill rule 1, then you need to increase height.

**Comment by chrisgoringe** [comment]
I've put this into #228 as part of making controller windows snap together, since they are quite related.

Since any code handling this will need to be rewritten when we have multiple controllers, I'm going to leave this as is for now.
