### ISSUE TITLE
[Bug] Value differences between Controller and node

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#250]
It's happening the same issue reported here: https://github.com/chrisgoringe/cg-controller/discussions/194#discussioncomment-11026738

![ksampler](https://github.com/user-attachments/assets/b1b62375-fd4d-407e-8f8b-9c5454ed9fb5)
![latent](https://github.com/user-attachments/assets/0f8a5c62-5140-4edf-8f54-6fcfe9ee37d8)

**Comment by JorgeR81** [comment]
What ranges and step sizes did you use ?

**Comment by LukeG89** [comment]
Same range in both nodes and 5 step in KSampler and 64 step in Latent (but I think you just need to put a number >1)

**Comment by JorgeR81** [comment]
Ah yes, for this to work, the min./max. values must be multiples of the step size.
The min. value can't be smaller than the step size ( for positve ranges ).

Like this:

![50](https://github.com/user-attachments/assets/86301046-26e2-4cc6-8cb7-ccbc0b3017c8)    ![rg2](https://github.com/user-attachments/assets/4fc3c9a5-0121-4868-a33b-5591d874132c)
  
![rg1](https://github.com/user-attachments/assets/0b628bb1-12cd-4113-b737-715b2dc9dc0b)

---

Maybe it could be easier and more reliable to have this restriction in the slider settings, instead of trying to adjust widget values.

Because these adjustments are a bit weird anyways.
For instance, with a step size of 5 we need to go from 1 to 5. But in then, we only have a step size of 4.

So, in the slider edit menu, the input boxes could turn red indicating invalid values. Like they do now, for other values.
And a pop up could show up indicating this rule.
It would be a litter harder for the user, but we would also be helping the user to create better and more prediable sliders.


![red](https://github.com/user-attachments/assets/2a7876aa-462d-4f67-8587-8fd844f58084)

**Comment by LukeG89** [comment]
Fixed!

**Comment by JorgeR81** [comment]
If we are going to do these automatic adjustments, wouldn't it make more sense to do it in the first step, instead of the last.

Because most of these will be caused by the need to use 1 instead of 0, for the min value ( e.g. KSampler steps ).

Now if  I set `min(1), max(50), step(5)` then I get: 1, 6, 11, ... 46, 50

But it would be more useful to have: 1, 5, 10, ... 45, 50

**Comment by chrisgoringe** [comment]
The rounding is done by the widget. While we might override, it's more
likely to cause the value mismatches that we have seen than accepting it.

Suggest you raise a new issue to look into it, but won't be changed again
soon.

**Comment by JorgeR81** [comment]
> While we might override, it's more likely to cause the value mismatches that we have seen than accepting it.

If it can cause more issues, then it's probably better to leave it like this.

I personally don't mind it, because I always use the "rule" I mentioned above:
( the min./max. values must be multiples of the step size ).
