### ISSUE TITLE
Maybe... widen controller if you try to make image taller

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#257]
Rather than stopping you from making the image taller, maybe make the controller get wider.

**Comment by JorgeR81** [comment]
This would be good to have, but as an user option.

Some users may not like this behaviour, because it may result in changing the controller size by accident, and having to adjust it afterwards. 

---
And if we enable this option, you could add another behaviour :

- making the Controller taller automatically, when we make the prompt box taller.
