### ISSUE TITLE
Widget heights stored per-node, so ... image in previous Controller get resized when you create and click on a new Controller window

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#264]

**Comment by LukeG89** [comment]
I think it is fixed after this commit: https://github.com/chrisgoringe/cg-controller/commit/cfa86ceba9b1d772cb43d69a76d483967b7e5a27

Now it keeps the size of the last resized image.

**Comment by LukeG89** [comment]
The resize issue is due to the fact that the new Controller window is probably smaller than the previous one, and the image widget inside is smaller as well, so when you update it keeps the last widget size and shrinks (or expands) the image in every windows.


https://github.com/user-attachments/assets/5c58288c-3c4d-4b48-84af-3531451f3177

**Comment by chrisgoringe** [comment]
Ah. The height of widgets (including images) is stored on a per-node basis, not a per-controller basis.

**Comment by chrisgoringe** [comment]
I think this should work a lot better now...

**Comment by LukeG89** [comment]
Works perfectly!🎉
