### ISSUE TITLE
[Bug] Controller windows can get stuck under topbar and sidebar

### ISSUE THREAD

**Issue by LukeG89** [chrisgoringe/cg-controller#295]
![controller_stuck](https://github.com/user-attachments/assets/966c152b-c51f-43b3-9b56-05698cf32cb4)

**Comment by JorgeR81** [comment]
Yes, same for me.

Snapping could fix this.

**Comment by JorgeR81** [comment]
After this update, some previews are very large.( e.g.: ControNet Preprocessor preview, and stage 2 KSampler live preview )  

I was testing this workflow a few minutes ago, because of other issues (https://github.com/chrisgoringe/cg-controller/issues/263#issuecomment-2458436317), but this was not happening:

![big](https://github.com/user-attachments/assets/3e1ca395-4274-4598-9c3d-ea323c6dc878)

**Comment by chrisgoringe** [comment]
That's because the maximum height for the images has been removed now we have the pin. Click the pin and they will shrink back down.

**Comment by JorgeR81** [comment]
Yeah, but there is another problem:

If the icon is white, now I can manually scale the image, beyond the limits of the Controller, so that part of the image is hidden (like in these images).

There is no break for the "resize" handle.

**Comment by chrisgoringe** [comment]
Yes, that is the expected behaviour.

Previously there was a size limit, so that it was easy to maximise the image without hiding any of it.

Now that can be done with the pin, so there is no reason to prevent someone making the image bigger if they want to. 

I use this to look at detail quite often. I don't see the problem :).

**Comment by JorgeR81** [comment]
> I use this to look at detail quite often.

If we're also able to click and drag the image to pan, it would be awesome !

**Comment by chrisgoringe** [comment]
> > I use this to look at detail quite often.
> 
> If we're also able to click and drag the image to pan, it would be awesome !

Added as #298
