### ISSUE TITLE
[ feature ] Show full image when "unpinning"

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#377]
When we remove automatic adjustment, the image could be resized, to show the full image.

Now we need to scroll the image down, to find the image resize handle.

I know we could also resize the Controller, but that's not convenient, if we have more snapped Controllers. 

---

![ag](https://github.com/user-attachments/assets/b266364d-9c6c-4228-9634-bec9db44c990)

**Comment by JorgeR81** [comment]
I realized that this may only work if there is a single image node in the Controller, right ?

I don't mind that.

**Comment by JorgeR81** [comment]
What would happen in this case ( see image ), with multiple nodes and only a small part of the image visible. 
The resulting image would be very small.

For consistency, I think this could work, even with multiple nodes. I think the user would expect that. 

But we could have a different rule.
The adjustment would only happen, if the resulting size has a minimum height ( e.g. %50 of the previous height ).

---

![img](https://github.com/user-attachments/assets/277282b3-8baa-4f69-a4de-511ae10c3c37)

**Comment by JorgeR81** [comment]
Instead of auto adjusting size, when "unpinning", we could have a right click option just for that.
I think this may be less confusing. 

We could right click the image, an have an option to : `adjust to available space`

But what would happen in the image is "pinned" ( blue icon ) ?
We have 2 alternatives: 

- We could hide this right click option ( but this way, the option would be less discoverable )
- This right click option would also "unpin" the image ( I think this would be the best approach )

---

And when "unpinning", we could do something else:

Instead of keeping the current ( max. ) size, we could return to a previous size, set by the user ( before "pinning" ).

**Comment by JorgeR81** [comment]
We could also consider replacing the "pin" icon.

With this extra functionality ( `fit to available space` ), the "pin" icon may be confusing.

What the "pin" icon does it's : `maximize image width`

Se we could have:

![ico](https://github.com/user-attachments/assets/b0821ef5-f805-41b8-b15b-0d6060cb2c58)

---

But maybe a cooler icon could be "lock".
Because we would be "locking", the resize handle. 

And since we have so many "lock" icons, we could use 2 of them,
( and maybe have only white icons, because they are less distracting ).

![ico1](https://github.com/user-attachments/assets/4794129e-5839-473f-928e-815ef5473190)

**Comment by chrisgoringe** [comment]
I'm a little confused... let me think this through:

We currently have two modes:

- pinned- fit image width to width of box, fix box vertical size to match aspect ratio
- unpinned - fit image height to height of box, maximum height determined by width 

As I understand it, the original issue was that if an image (pinned) was not fully visible because of the size of the controller (and the scroll position?) unpinning it left it in that state. 

The original suggestion was that in this case, in the act of unpinning, the box could be shrunk down so that it is fully visible.

That seems relatively simple to do.

Then there is the concern that this might make the image too small. But in that case, the resize corner would be immediately accessible, and it's trivial to scale it up a bit.

So... maybe I'll implement the above, and we can all see what we think!

**Comment by chrisgoringe** [comment]
Have a play with the version on dev

**Comment by JorgeR81** [comment]
Yeah, it works well.

Now If I change the heigh of the controller, ( e.g. to have more space for the prompt ), 
I can click the "pin" icon twice ( "pin" and "unpin" ), to adjust in image to the space avaliable.

I just thought it would be more straightforward to have an option just to do that. 

But I guess this works too.
It's faster to click the icon twice, than to right click, find to opion an click again. 

---

![pic](https://github.com/user-attachments/assets/0bddd70e-2af8-4635-8f01-c42af7f8456a)
