### ISSUE TITLE
Select nodes directly instead of by color (was Allow control to be chosen by shapes)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#45]

**Comment by Amorano** [comment]
> So if we forget the advanced controls, there is just one simple rule:
> 
>     * **All nodes with a box shape will be added to the Controller**
>       This will match the box shapes in the controller.
>       It would be easy for the users to understand and remember this setting.

No thanks. My default is Box shapes for ALL nodes. I dont want all of the controls added just because of my workflow.

Same for "colors" really. This should be a key combo that triggers a menu item (add to controller). 

It would be much better to *NOT* hijack UI to use for populating other things, unless the node is marked to do so.

Why? Lots of reasons, like I said with the shapes, some people have color-blindness problems.

**Comment by JorgeR81** [comment]
> It would be much better to NOT hijack UI to use for populating other things, unless the node is marked to do so.

Yeah, maybe that would be the best solution.

@chrisgoringe, Could you reconsider this ?

We could have an option to `add to controller` in the node's right click menu.

And the nodes could have an icon, in the top right corner, or something, to visually indicate they were added to the Controller.

**Comment by chrisgoringe** [comment]
Yeah, I think you've convinced me.

The idea behind (re)using colors was that we could have more than one panel. But that functionality is now down (much better) with the groups.

I'll do a right-click menu.
