### ISSUE TITLE
Refresh button and/or periodic refresh (Controller doesn't update when...)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#82]
... node title changes
... node color changes
... group name changes
... node moves in or out of group
... widget edited directly on node

You can always hide-then-show, so this isn't a major issue. Just tracking...

(Fixed)
_... node mode (bypass state) changes_

**Comment by chrisgoringe** [comment]
mode can be tracked (0.9.2.1)

**Comment by JorgeR81** [comment]
Well if nothing else works, you can always add the manual update again.  

But instead of the right click menu, maybe having a refresh icon / button on the Controller top's left or right corner. 

I think this would be OK, because:

- The browser has refresh button

- ComfyUI has a refresh button ( for when  we add new models to folders ) .

![ref](https://github.com/user-attachments/assets/608c3833-53ce-4f94-b16c-092f99acb5f8)

**Comment by JorgeR81** [comment]
And a manual update could also be a fix for this issue: https://github.com/chrisgoringe/cg-controller/issues/85

**Comment by chrisgoringe** [comment]
Added a periodic request which runs in the background. Tries once every five seconds, so very low impact.
