### ISSUE TITLE
Toggle _group_ bypass

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#89]

**Comment by JorgeR81** [comment]
For a less complex GUI, instead of the individual node toggles, we could have a group bypass toggle, next to the group selector.

Normally, I have individual groups for each Controlnet, IPAdapter, Upscaler, etc ...

I think bypassing the whole group ( with Loaders, etc ... ), instead of the just the specific "Apply" node, would have the same result. 

To show the bypass button, we just select the group we want.

![bt](https://github.com/user-attachments/assets/6c6bbdc4-ff10-45d6-ac69-92a0adfdbe11)

**Comment by chrisgoringe** [comment]
> * a clickable bypass button, on the top right
> * It does not need to be a big toggle button. It could be icons:  ( https://www.svgrepo.com/svg/503241/bypass )
>   rgthree also uses clickable icons to bypass, in group headers:

**Comment by JorgeR81** [comment]
Ah OK, so you're thinking on the icons for the group toggles.
And no individual node bypass.

I was worried about bypassing nodes that are not displayed in the Controller (  https://github.com/chrisgoringe/cg-controller/issues/72#issuecomment-2408527838 )
But if the GUI is not misleading, it should be fine. The icons may help on this !

**Comment by LukeG89** [comment]
There is a problem with Loader nodes


https://github.com/user-attachments/assets/b1c031d0-da03-47f7-814f-56bebb120d55

**Comment by chrisgoringe** [comment]
So the problem is the workflow not updating until you move out of the controller?

**Comment by LukeG89** [comment]
Yep!

**Comment by chrisgoringe** [comment]
ok, fixed

**Comment by JorgeR81** [comment]
I still have this issue. 
Also in the version that ships wih ComfyUI.
The Controller is not updated when I click bypass.

**Comment by chrisgoringe** [comment]
That is #291 not this issue
